# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

storage:
  type: postgres
  # path: "postgres://${POSTGRESQL_DB_USERNAME}:${POSTGRESQL_DB_PASSWORD}@${POSTGRESQL_DB_HOSTNAME}:${POSTGRESQL_DB_PORT}/${POSTGRES_DB}?sslmode=disable"
  path: "${POSTGRESQL_DB_CONNECT_STRING}"

# announcements:
#   - timestamp: 2025-08-15T14:00:00Z
#     type: outage
#     message: "Scheduled maintenance on database servers from 14:00 to 16:00 UTC"
#   - timestamp: 2025-08-15T16:15:00Z
#     type: operational
#     message: "Database maintenance completed successfully. All systems operational."
#   - timestamp: 2025-08-15T12:00:00Z
#     type: information
#     message: "New monitoring dashboard features will be deployed next week"

# alerting:
#   mattermost:
#     webhook-url: "${MATTERMOST_WEBHOOK_URL}"
#     client:
#       insecure: true

endpoints:
  - name: Ubuntu.com
    group: Websites
    url: "https://ubuntu.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
    alerts:
      - type: mattermost
        description: "Ubuntu.com is down"
        send-on-resolved: true

  - name: GitHub
    group: Websites
    url: "https://github.com"
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"
    alerts:
      - type: mattermost
        description: "GitHub is down"
        send-on-resolved: true

  - name: PostgreSQL
    url: "tcp://${POSTGRESQL_DB_HOSTNAME}:${POSTGRESQL_DB_PORT}"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
