; Copyright 2026 Canonical Ltd.
; See LICENSE file for licensing details.

# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
toxworkdir = {env:HOME}/.tox_local/gatus-operator
no_package = True
skip_missing_interpreters = True
env_list = format, lint, unit, static, coverage-report
min_version = 4.0.0

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
# Use uv to install packages
allowlist_externals = uv
install_command = uv pip install {opts} {packages}
set_env =
    PYTHONPATH = {tox_root}/lib:{[vars]src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS
    ROCK_IMAGE
    OCI_RESOURCE_NAME

[testenv:format]
description = Apply coding style standards to code
deps =
    ruff
commands =
    ruff format {[vars]all_path}
    ruff check --fix {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards, and static checks
dependency_groups =
    lint
    unit
    integration
commands =
    # if this charm owns a lib, uncomment "lib_path" variable
    # and uncomment the following line
    # codespell {[vars]lib_path}
    codespell {tox_root}
    ruff check {[vars]all_path}
    ruff format --check --diff {[vars]all_path}
    pyright {posargs}

[testenv:unit]
description = Run unit tests
dependency_groups =
    unit
commands =
    coverage run --source={[vars]src_path} -m pytest \
        -v \
        -s \
        --tb native \
        {[vars]tests_path}/unit \
        {posargs}

[testenv:integration]
description = Run integration tests
dependency_groups =
    integration
pass_env =
    {[testenv]pass_env}
    # The integration tests don't pack the charm. If CHARM_PATH is set, the tests deploy the
    # specified .charm file. Otherwise, the tests look for a .charm file in the project dir.
    CHARM_PATH
commands =
    pytest \
        -v \
        -s \
        --tb native \
        --log-cli-level=INFO \
        {[vars]tests_path}/integration \
        {posargs}

[testenv:coverage-report]
description = Create test coverage report
dependency_groups =
    unit
commands =
    coverage report

[testenv:static]
description = Run static analysis tests
dependency_groups =
    static
commands =
    bandit -c {toxinidir}/pyproject.toml -r {[vars]src_path} {[vars]tests_path}

[testenv:reqs]
description = Update requirements.txt from pyproject.toml using uv
allowlist_externals = uv
commands =
    uv export --no-dev --no-hashes -o requirements.txt
