# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Publish to edge

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    secrets: inherit
    with:
      channel: latest/edge
      # Map the 'gatus' resource built by Rockcraft and published to GHCR
      # to the 'app-image' resource expected by the charm.
      resource-mapping: '{"gatus": "app-image"}'

